version: '3'

services:
  node:
    build: .
    tty: true
    ports:
      - "5000:5000"
      - "5001:5001" # liveload
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - default